name: source_gen_test
version: 1.3.2
description: >-
  Test support for the source_gen package.
  Includes helpers to make it easy to validate both success and failure cases.
repository: https://github.com/kevmoo/source_gen_test

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^9.0.0
  build: ^4.0.3
  build_test: ^3.5.4
  dart_style: ^3.1.3
  meta: ^1.16.0
  path: ^1.9.0
  source_gen: ^4.1.1
  test: ^1.27.0

dev_dependencies:
  collection: ^1.19.0
  dart_flutter_team_lints: ^3.0.0
