name: source_gen_test
version: 0.1.1-dev
description: >-
  Test support for the source_gen package.
  Includes helpers to make it easy to validate both success and failure cases.
author: Kevin Moore <github@j832.com>
homepage: https://github.com/kevmoo/source_gen_test

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: '>=0.35.3 <0.40.0'
  build: ^1.2.2
  build_test: '>=0.10.12 <2.0.0'
  dart_style: ^1.2.0
  meta: ^1.0.2
  path: ^1.3.2
  source_gen: ^0.9.4
  test: ^1.3.3

dev_dependencies:
  pedantic: ^1.0.0
